export const SET_API_TOKEN = 'SET_API_TOKEN ';
export const SET_EGM_LIST = 'SET_EGM_LIST';
export const SET_SELECT_EGM = 'SET_SELECT_EGM';
export const SET_ON_ACTION_EGM_LIST = 'SET_ON_ACTION_EGM_LIST';
export const SET_WS_CLIENT = 'SET_WS_CLIENT';
export const SET_EGM_CONNECT_STATE_LIST = 'SET_EGM_CONNECT_STATE_LIST';
