export const EGM_SET_EGM_LIST = 'EGM_SET_EGM_LIST';
export const EGM_SET_EGM_CONNECT_FAIL_LIST = 'EGM_SET_EGM_CONNECT_FAIL_LIST';
export const EGM_SET_EGM_REMOVE_FAIL_LIST = 'EGM_SET_EGM_REMOVE_FAIL_LIST';
export const EGM_SET_EGM_PLAYING_LIST = 'EGM_SET_EGM_PLAYING_LIST';
export const EGM_SET_EGM_CREDIT_LIST = 'EGM_SET_EGM_CREDIT_LIST';
export const EGM_SET_SELECT_EGM_DATA = 'EGM_SET_SELECT_EGM_DATA';
export const EGM_SET_KICK_LIST = 'EGM_SET_KICK_LIST';
