export const EGM_SET_EGM_LIST = 'EGM_SET_EGM_LIST';

export const EGM_SET_SELECT_EGM_DATA = 'EGM_SET_SELECT_EGM_DATA';

// Connect
// export const EGM_SET_EGM_CONNECT_FAIL_LIST = 'EGM_SET_EGM_CONNECT_FAIL_LIST';
// export const EGM_SET_EGM_REMOVE_FAIL_LIST = 'EGM_SET_EGM_REMOVE_FAIL_LIST';
export const EGM_SET_EGM_CONNECT_SUCCESS_LIST = 'EGM_SET_EGM_CONNECT_SUCCESS_LIST';
export const EGM_SET_EGM_CONNECT_REMOVE_SUCCESS_LIST = 'EGM_SET_EGM_CONNECT_REMOVE_SUCCESS_LIST';

// Playing
export const EGM_SET_EGM_PLAYING_LIST = 'EGM_SET_EGM_PLAYING_LIST';
export const EGM_REMOVE_IS_PLAYING = 'EGM_REMOVE_IS_PLAYING';

// Credit
export const EGM_SET_EGM_CREDIT_LIST = 'EGM_SET_EGM_CREDIT_LIST';

// Kick
export const EGM_SET_KICK_LIST = 'EGM_SET_KICK_LIST';
